measure2Dpower-mm.py
nbodykit/measurepower.py

function measure2Dpower returns k, mu, P, N, edges where
edges is [kedges, muedges]. N is the number of modes in each bin

added driver and backend function to measure 2D power

---

nbodykit/files.py

Please pull the changes to TMP snapshot

Modified files.TPMSnapshotFile to rea in velocity.

---

power.py

Please pull the change. Thanks.

Moved parser to top.

---

contrib/CollapsedHaloMatter.py

This painter measures the power spectrum when all particles
of selected halos are moved to the center of mass.
I am growing more uncomfortable about mixing IO and painting.
but maybe this is the way it is.

Add a 'collapsed halo matter' painter.

---

measure2Dpower-mm.py

Please pull the code for 2Dpower redshift distorted.

Pulling the redshift distortion

---

power.py

Use a regex to split the spaces and quotations correctly.

fix preparser with @syntax.

---

contrib/CollapsedHaloMatter.py
contrib/MBIIDMO.py
contrib/MWhiteHaloFile.py
nbodykit/files.py
nbodykit/measurepower.py
nbodykit/pkmuresult.py
nbodykit/plugins/HDFPainter.py
nbodykit/plugins/HaloFilePainter.py
nbodykit/plugins/PandasPlainTextPainter.py
nbodykit/plugins/PlainTextPainter.py
nbodykit/plugins/TPMSnapshotPainter.py
nbodykit/plugins/__init__.py
power.py

* fixes cross power calculation and introduces new logic in power.py and measurepower.py
to handle both the auto and cross cases
* for fields c1, c2, power should be c1.real x c2.real + c1.imag x c2.imag
* introduces new plain text and HDF5 painter classes

fix for cross power calculation; new ascii/hdf5 painters

---

nbodykit/files.py

Important behavior change is now we requite the dictionary syntax
of columns. (A['c'] vs A.c)
Otherwise, this change is mostly about names in the parser and evaluator.

update eval of selection mini-language.

---

measure_dprof.py

Please pull the new density profile calculator, Thanks!

density profile calculator

---

part_in_hal_npara.py
rpbmass_fof.py

Added the mass replacing script, as well as getting the formatting done! We have a logo when nbodykit is ran!

Added a python script for replacing simulation mass of halos with Nbody.

---

nbodykit/measurepower.py

Previously mu = 1.0 was always excluded; the old behavior wasn't
exactly wrong, but it breaks the compatibility with 1d spectrum(
by less than 1% in position of mean k, systematically)

Makes the last mu bin inclusive (including mu == 1.0).

---

measure_dprof.py
nbodykit/files.py
nbodykit/plugins/HaloFilePainter.py
rpbmass_fof.py
shrink_halos.py

paving the way for reading MB-II and BlueTides snapshots.

give files.py a uniform 'read' and 'write' interface.

---

nbodykit/utils/selectionlanguage.py
sort_by_label.py

Not the best way for missing values, but ...

Add nan support to the selectionlanguage

---

nbodykit/measurepower.py
power.py

* can pass desired multipole numbers to ``poles`` option of ``power.py``
* also must then specify the name of the multipoles output file via ``poles_output`` option
* writes out 2D P(k,mu) result file to ``output`` and multipole results as well

initial commit of multipoles functionality

---

contrib/ClosePairsBias.py

Reader for the Close Pair Bias Project.
It reads the hdf5 format halo catalogue and adds a Proximity column, which is defined
as the distance to the nearest halo that's most massive than a threshold.

Closepairbias

---

contrib/MBIIDMO.py
corr.py
examples/power/test_tpmsnapshot_1d_corr.params
nbodykit/measurepower.py
nbodykit/pkmuresult.py
power-parallel.py
power.py

The interface and logic in measurepower() is hugely simplified.
It does no more than project the 3D power spectrum to a prefered basis,
be it 1d, (k,mu), or (k, poles)
This commit paves the way to reuse the code in measurepower.py to measure
correlation function, in 1d, (k,mu) or (k, poles).

Refactor measurepower and power.py

---

.gitignore
README.rst
contrib/BOSSChallengeMock.py
nbodykit/files.py
requirements.txt
setup.py

-- see 3b87812 and README for discussion of using pip install -- seems like pip install is the much more flexible way of handling dependencies and user-customization 
-- instructions in README work on my mac -- still need to test edison and update README

using pip install and adding requirements.txt for dependencies

---

.travis.yml
README.rst
bin/fof.py
bin/power.py
bin/subhalo.py
examples/fof/run.sh
examples/power/run.sh
examples/subhalo/run.sh
examples/trace-halo/run.sh
nbodykit/plugins/__init__.py

Add travis tests and ensure python 3 support.
So we do run on python 3, after all.

Travis and 3

---

bin/fof.py
bin/power-parallel.py
bin/power.py
bin/subhalo.py
bin/trace-halo.py
contrib/BOSSChallengeMock.py
contrib/ClosePairsBias.py
contrib/CollapsedHaloMatter.py
contrib/MBIIDMO.py
contrib/MWhiteHaloFile.py
contrib/QPMMock.py
nbodykit/files.py
nbodykit/plugins/DataSource/HDF5.py
nbodykit/plugins/DataSource/Pandas.py
nbodykit/plugins/DataSource/PlainText.py
nbodykit/utils/mpilogging.py

I remembered we were going to do this and never got around to it

merging in mpilogger changes 

---

.travis.yml
bin/power.py
bin/subhalo.py
examples/subhalo/test_tpmsnapshot.params
nbodykit/distributedarray.py
nbodykit/halos.py
nbodykit/pkmuresult.py
nbodykit/plugins/Power1DStorage.py
nbodykit/plugins/Power2DStorage.py
nbodykit/plugins/__init__.py
nbodykit/utils/pluginargparse.py
runtests.sh
setup.py

The examples run on python 3.
Contrib hasn't been checked yet.

Python 3 is alive.

---

bin/corr-parallel.py
bin/corr.py
bin/power-parallel.py
bin/power.py
examples/corr/run.sh
examples/corr/test_mwhite_halo_1d.params
examples/corr/test_mwhite_halo_2d.params
examples/corr/test_mwhite_halo_poles.params
nbodykit/files.py
nbodykit/measurestats.py
nbodykit/utils/taskmanager.py
runtests.sh

also added some tests for the corr.py calls

corr.py does multipoles now -- needs latest version of  kdcount

---

examples/corr/test_cross_corr.params
nbodykit/measurestats.py

Duplicate transfer and painter to len(field) if a scalar is provided.

---

contrib/BOSSChallengeMock.py
nbodykit/files.py
nbodykit/measurestats.py
nbodykit/plugins/Measurement1DStorage.py
nbodykit/utils/taskmanager.py

removing factor of 1/2 in ell pre-factor; 1D reader returns cols as meta

---

examples/corr/run.sh
examples/power/run.sh
examples/subhalo/run.sh
examples/trace-halo/run.sh

Hoping we can catch more errors like #101 with this..

Run all tests with 2 processes.

---

bin/subsample.py
examples/subsample/run.sh
examples/subsample/test_tpmsnapshot.params

Working towards #117 
The script will write a hdf5 file. Need a tool to convert between subsample to hdf5 to drive qpm_calc_xi.. Or write our new qpm_calc_xi that takes hdf5.

WIP: Subsample

---

nbodykit/dataset.py

API update for several areas of `DataSet`

---

bin/corr.py
bin/nbkit.py
examples/corr/run.sh
examples/corr/test_cross_corr.params
examples/corr/test_mwhite_halo_1d.params
examples/corr/test_mwhite_halo_2d.params
examples/corr/test_mwhite_halo_poles.params
nbodykit/__init__.py
nbodykit/extensionpoints.py
nbodykit/measurestats.py
nbodykit/plugins/algorithms/PairCountCorrelation.py
nbodykit/plugins/algorithms/PeriodicPower.py

Only working example so far replaces corr.py. Just want to see what @rainwoodman thinks before doing the major code overhaul. I think this is a definite improvement over what we have
the only new commit is 0046a1b. see message there for more description.

first pass at implementing `Algorithm` extension point

---

bin/subhalo.py
bin/subsample.py
bin/trace-halo.py
contrib/BOSSChallengeMock.py
contrib/MWhiteHaloFile.py
contrib/QPMMock.py
examples/corr/test_cross_corr.params
examples/fof/test_fastpm.params
examples/power/test_cross_power.params
examples/power/test_fofgroups.param
nbodykit/extensionpoints.py
nbodykit/fof.py
nbodykit/measurestats.py
nbodykit/plugins/datasource/FOFGroups.py
nbodykit/plugins/datasource/FastPM.py
nbodykit/plugins/datasource/Gadget.py
nbodykit/plugins/datasource/HaloLabel.py
nbodykit/plugins/datasource/TPMSnapshot.py

This PR 
1) adds 'finalize_attributes' interface to the plugins, (replacing 'initialize(args)')
2) fixes a rare bug in MWhiteHalo plugin due to a numpy bug
3) moves comm in DataSource to .create, such that it can be used in fianlize_attributes.
4) mark boxsize optional for several DataSources where BoxSize is stored in the file already.

Datasourceinit

---

bin/nbkit.py
examples/power/run.sh
examples/power/test_cross_power.params
examples/power/test_fofgroups.param
examples/power/test_mwhite_halo.params
examples/power/test_pandas_hdf.params
examples/power/test_pandas_text.params
examples/power/test_plaintext.params
examples/power/test_tpmsnapshot_1d.argparse
examples/power/test_tpmsnapshot_1d.params
examples/power/test_tpmsnapshot_1d_corr.params
examples/power/test_tpmsnapshot_2d.params
nbodykit/extensionpoints.py
nbodykit/plugins.py
nbodykit/plugins/algorithms/PeriodicPower.py

This PR implements:
* `ReadConfigFile` action in `nbodykit.plugins` that reads a YAML file and checks various things using the underlying parser actions
* plugins.ArgumentParser returns namespace from YAML file when passed via `-c`, `--config`; the preparser also loads any plugins specified with `X` in YAML file
* PeriodicPower algorithm now working
* power examples updated to use nbkit.py PeriodicPower and the -c syntax (or @filename for one case) 
* no changes so far to power.py -- everything there should still work

Adding PeriodicPower with working YAML reader and cmd-line parser combo

---

examples/batch/extra.template
examples/batch/run.sh
examples/batch/test_power_batch.template
nbodykit/utils/taskmanager.py
runtests.sh

specify cpus per parallel worker now; tests of nbkit-batch.py

---

examples/tidaltensor/run.sh
examples/tidaltensor/test_tpmsnapshot.params
nbodykit/plugins/algorithms/TidalTensor.py
runtests.sh

This PR implements a Tidal Tensor calculator.

Tidal Tensor

---

examples/fof/test_fastpm.params
nbodykit/fof.py
nbodykit/plugins/algorithms/FOF.py
nbodykit/plugins/datasource/FastPM.py

This only support FastPM files for now. It obviously is point at
some refactoring and multi data stream thing..

Add a flag in FOF to find Initial Position of halos.

---

nbodykit/distributedarray.py
nbodykit/extensionpoints.py

I added the helper function to distributedarray.py....sort of a similar topic? objections, @rainwoodman?

helper function to Scatterv arrays; use in DataSource.read 

---

nbodykit/cosmology.py
nbodykit/distributedarray.py

the remainder of the array split wasn't getting scattered...

bug fix in ScatterArray

---

nbodykit/extensionpoints.py

DataCache should store the local size of data (for filling in defaults)

---

bin/nbkit.py
nbodykit/distributedarray.py
nbodykit/extensionpoints.py
nbodykit/measurestats.py
nbodykit/plugins/algorithms/BianchiFFTPower.py
nbodykit/plugins/algorithms/PeriodicBox.py

* some of algorithms were handling logging levels independently of nbkit.py 
* this simplifies and unifies the logging levels -- can use the '-v', '--verbose' option to set logging level
to DEBUG instead of INFO
we can make more changes in the future, but I think this is a good simplification

simplifies logging in nbkit.py -- default is INFO, -v option makes it DEBUG

---

nbodykit/extensionpoints.py
nbodykit/utils/config.py

better error messages for failed plugin parsing 

---

docs/conf.py

* the ``import nbodykit`` means the custom modules have to be there
* get around this using the mock modules

RTD back to building successfully; have to mock a bunch of modules

---

nbodykit/plugins/algorithms/BianchiFFTPower.py

so far, this adds a P(k,mu) calculation to the Bianchi algorithm

Add a development branch specifically for Lucas's work 

---

nbodykit/plugins/algorithms/BianchiFFTPower.py

This reverts commit 013e91fbb61ac895f30903dd7bc01c343c9ecda4, reversing
changes made to 93a6eb7ea8559434734459b104f4bf4ee86514ad.

This reverts the accidental merge of the ``lucas-dev`` branch into master

---

examples/boxsize/run.sh
examples/boxsize/test_boxsize.params
nbodykit/fkp.py
nbodykit/plugins/algorithms/TestBoxSize.py
runtests.sh

* this has come up a few times in the Bianchi algorithm, where the user needs to find more info about out-of-bounds particles
* this saves to a file the index of the out-of-bounds particles and which dimensions the particle is out-of-bounds in

adds a simple utility algorithm ``TestBoxSize`` that finds out-of-bounds particles easily

---

nbodykit/extensionpoints.py

DataSource is based on DataSourceBase.

Multiple extensionpoints based on the same base class.

---

.travis.yml
examples/cache_manager.py
nbodykit/test/__init__.py
nersc/nightly-build.sh

fixes #199 
need to redirect PYTHONUSERBASE, otherwise pip will look for packages there, if not first in the local lib/ directory

redirect the python user base in nightly build

---

bin/nbkit-batch.py
bin/nbkit.py

Prettier logging messages.

---

examples/power/test_pandas_plaintext.params
examples/power/test_plaintext.params
nbodykit/ndarray.py
nbodykit/plugins/datasource/Pandas.py
nbodykit/plugins/datasource/PlainText.py
nbodykit/plugins/datasource/RaDecRedshift.py
nbodykit/test/test_selection.py
nbodykit/test/test_subhalo.py
nbodykit/utils/selectionlanguage.py

implements a few new features in selection language: 
* vector indexing via "Position[:,0]"
*  log, log10, exp functions can be used on either side of comparison, i.e., "log10(Mass) < 12" or "LogMass < log10(10**12)"
* better exception handling -- an error is thrown if selection array is multidimensional, i.e., "Position < 100" or "Position[:,:2] < 100" will throw an error
* functionality for "is not", i.e., "Mass is not nan"
* adding a unit test suite  for selection language
This also cleans up the selection query in Pandas and Plaintext data sources (and implements new examples, so reload the cache) such that the builtin columns (Position, Velocity, etc) can also be selected

indexing + basic functions for selection language

---

nbodykit/measurestats.py

* this cleans up the memory usage in compute_bianchi_poles() by removing a few extra copies 
* probably not optimal memory usage, but fixes #206 related to memory issue on Edison

cleaning up memory usage in BianchiFFTPower

---

examples/power/test_pandas_plaintext.params
nbodykit/utils/config.py

* implements case insensitive parsing of names when comparing names in the Schema and configuration file 
* adds some more documentation
Is that what you had in mind @rainwoodman ?

case insensitive parsing of configuration file names

---

nbodykit/fkp.py
nbodykit/plugins/algorithms/RedshiftHistogram.py
nbodykit/test/test_batch.py
nbodykit/test/test_boxsize.py
nbodykit/test/test_corr.py
nbodykit/test/test_dataset.py
nbodykit/test/test_describe.py
nbodykit/test/test_fiber_collisions.py
nbodykit/test/test_fkp.py
nbodykit/test/test_fof.py
nbodykit/test/test_paint.py
nbodykit/test/test_power.py
nbodykit/test/test_subhalo.py
nbodykit/test/test_subsample.py
nbodykit/test/test_tidaltensor.py
nbodykit/test/test_tracehalo.py
nbodykit/test/test_zhist.py
nbodykit/test/utils/asserts.py
nbodykit/test/utils/datasource.py
nbodykit/test/utils/pipeline.py
nbodykit/test/utils/results.py

two new additions: 
* test module for FKPCatalog for all of the various input scenarios
* FKPCatalog now can handle FKPWeight and Weight

adds a test module for FKPCatalog and Weight/FKPWeight breakdown

---

nersc/nightly-build.sh

this closes #230 
everything appears to be working on edison...updating Cori now

build multiple python versions in same bundle for nightly NERSC build

---

nbodykit/plugins/algorithms/PaintGrid.py
nbodykit/plugins/datasource/BigFileGrid.py
nbodykit/plugins/datasource/FastPM.py

Silly silly ones.
Means we need to revisit the test cases.

Bugs found edison

---

bin/nbkit-batch.py

read config files on root before bcast in nbkit-batch

---

.travis.yml
nbodykit/__init__.py
nbodykit/algorithms/fftpower.py
nbodykit/algorithms/paint.py
nbodykit/base/grid.py
nbodykit/base/particles.py
nbodykit/io/__init__.py
nbodykit/io/hdf.py
nbodykit/measurestats.py
nbodykit/source/__init__.py
nbodykit/source/grid/__init__.py
nbodykit/source/grid/bigfile.py
nbodykit/source/grid/linear_grid.py
nbodykit/source/particle/from_file.py
nbodykit/source/particle/zeldovich.py
nbodykit/tests/test_grid.py
nbodykit/tests/test_io.py
nbodykit/tests/test_lab.py

* test case added for HDF file
* test cases added for linear grid and bigfile grid
addresses #249

adds HDF support and Grid sources

---

nbodykit/algorithms/fftpower.py
nbodykit/tests/test_fftpower.py
nbodykit/utils.py

had to work out a few kinks regarding to numpy, but
in the end we basically saves the entire thing as a dictionary in a
plain text format.

FFTPower saves to json.

---

.travis.yml
nbodykit/algorithms/__init__.py
nbodykit/algorithms/bianchi.py
nbodykit/algorithms/fftpower.py
nbodykit/algorithms/zhist.py
nbodykit/base/particlemesh.py
nbodykit/base/particles.py
nbodykit/cosmology/core.py
nbodykit/dataset.py
nbodykit/lab.py
nbodykit/source/particle/__init__.py
nbodykit/source/particle/fkp.py
nbodykit/source/particle/from_file.py
nbodykit/source/particle/from_numpy.py
nbodykit/source/particle/uniform.py
nbodykit/source/particle/zeldovich.py
nbodykit/tests/test_bianchi.py
nbodykit/tests/test_fftpower.py
nbodykit/tests/test_zhist.py
nbodykit/transform.py
nbodykit/utils.py

in addition to Bianchi algorithm and source, biggest change is probably reliance on "cachey" + dask.cache to cache "compute" calls in Sources (if not installed, warning is printed)

WIP: adding Bianchi algorithm + cache functionality for Sources

---

nbodykit/algorithms/convpower.py
nbodykit/algorithms/fftpower.py
nbodykit/algorithms/threeptcf.py
nbodykit/base/particles.py
nbodykit/dataset.py
nbodykit/io/csv.py

This adds an algorithm for Zack's 3PT CF estimator. Independently verified against a c++ version, but no test case added yet
Also:
* a few changes to DataSet related to naming dimensions 
* a few fixes in CSVFile to handle some more advanced `read_csv` keywords

multipoles of 3-pt correlation function

---

nersc/activate.sh
nersc/nightly-build.sh

this fixes #314 
- fixes bug in activate.sh
- fixes pip versioning issue in nightly-build.sh

fix activate.sh

---

nbodykit/base/mesh.py
nbodykit/tests/test_lab.py

Closes #324; but this is an incompatible change.

.apply is no longer inplace. It creates a view with extended 'actions'.

---

nbodykit/base/catalogmesh.py

compensation shall allways be applied first.

---

nbodykit/algorithms/fibercollisions.py
nbodykit/source/catalog/hod.py
nbodykit/source/catalog/tests/test_hod.py
nbodykit/source/catalog/uniform.py

set random seed when it is None (#329)

---

nbodykit/base/mesh.py
nbodykit/source/mesh/tests/test_grid.py
nbodykit/tests/test_lab.py

maybe the save method shall be moved to the mesh object?

Remove cyclic reference in mesh.to_field().save.

---

nbodykit/source/catalog/array.py
nbodykit/source/catalog/tests/test_catalog.py

This adds support of a dictionary input to an array source. useful for quickly creating an array catalog from known Position and Velocity.

support Dictionary input in an array source.

---

nbodykit/algorithms/__init__.py
nbodykit/algorithms/fftpower.py
nbodykit/algorithms/tests/test_fftpower.py

This adds a ProjectedFFTPower algorithm that projects the field to selected axes and compute the power spectrum. Like 1d power in forest and 2d power in lensing.

Projected power

---

nbodykit/algorithms/paircount.py

This is a temporary workaround of #364 that allows SurveyDataPairCount to be useable. Currently, unbalanced decomposition of objects across ranks leads to unreasonably long run times.

Remove domain decomposition from SurveyDataPairCount

---

nbodykit/base/catalog.py
nbodykit/base/tests/test_catalog.py

This PR fixes #380, and adds pretty print for #375.

Add a subclass of da.array, ColumnAccessor.

---

README.SGI-MPT

@nickhand -- probably include some form of this in the documentation at some point...

Add a readme for using with SGI-MPT.

---

nbodykit/algorithms/fftpower.py
nbodykit/source/catalog/species.py
nbodykit/source/catalog/tests/test_species.py

I didn't know if the base class test was intentially or not, thus leaving this as a PR..

Enable FFTPower directly with MultipleSpeciesCatalog

---

nbodykit/cosmology/cosmology.py
nbodykit/cosmology/tests/test_cosmology.py

I am not sure how desirable this is. I do find it a bit confusing that Omega_cdm in __init__ becomes Omega0_cdm in the attribute.

Param with zeros

---

nbodykit/base/catalog.py
nbodykit/source/catalog/species.py
nbodykit/source/catalogmesh/species.py
nbodykit/transform.py

rename catalogcopy -> catalogsubset

---

nbodykit/base/catalog.py
nbodykit/source/catalog/fkp.py
nbodykit/source/catalog/species.py
nbodykit/source/catalogmesh/fkp.py

A couple of things:
- this makes the criteria to apply optimized selection successfully stricter
- add an optimization where we do not do selection if the input index does not change the size
- several fixes for FKP related to how the internal columns needed for painting are computed

make optimized selection more robust + FKP fixes

---

nbodykit/cosmology/cosmology.py
nbodykit/cosmology/tests/test_cosmology.py

better error handling for deprecated args in Cosmology

---

docs/source/catalogs/overview.rst
nbodykit/algorithms/cgm.py
nbodykit/base/catalog.py
nbodykit/base/tests/test_catalog.py

this is useful for abundance matching.

Add a rank column

---

nbodykit/algorithms/cgm.py

fix future warning in pandas 0.21

---

CHANGES.rst
nbodykit/algorithms/pair_counters/base.py
nbodykit/algorithms/pair_counters/corrfunc/base.py
nbodykit/algorithms/pair_counters/mocksurvey.py
nbodykit/algorithms/pair_counters/simbox.py
nbodykit/algorithms/paircount_tpcf/estimators.py
nbodykit/algorithms/paircount_tpcf/tests/test_1d.py
nbodykit/algorithms/paircount_tpcf/tests/test_2d.py
nbodykit/algorithms/paircount_tpcf/tests/test_angular.py
nbodykit/algorithms/paircount_tpcf/tests/test_projected.py
nbodykit/algorithms/paircount_tpcf/tpcf.py

Adematti landyszalay

---

nbodykit/algorithms/fof.py

This feature is useful if we want to run FOF on survey geometry data,
e.g. a lightcone.

ENH: Allow over decomposition in FOF.

---

CHANGES.rst
nbodykit/algorithms/cgm.py

fix for the stricter error introduced by
https://github.com/pandas-dev/pandas/pull/19230

update cgm for pandas-0.23.0

---

nbodykit/base/catalog.py
nbodykit/base/tests/test_catalog.py

This deprecates datasets=[], which is clumsier.

Add dataset= argument to Catalog.save

---

nbodykit/source/mesh/catalog.py

If some ranks receive too many partilces, throttle the chunksize.
This fixed random OOM errors, which may be the true cause of #525.
The current solution is not ideal. It is possible that the number
of particles on some ranks will not decrease as we decrease chunksize.
We can look into fixing that when it becomes a real problem.

Throttle during painting.

---

nbodykit/base/mesh.py
nbodykit/binned_statistic.py

Stop triggering two deprecation warnings from pmesh and numpy.

fix two warnings.

---

nbodykit/tests/test_transform.py
nbodykit/transform.py

This also adds HaloSigma, the velocity dispersion of DM,
based on a single model Martin White suggested.

Vectorize Halo transformation functions against redshift.

---

nbodykit/source/mesh/catalog.py
nbodykit/source/mesh/tests/test_catalogmesh.py

The error was introduced in #531 .

Fix index error in painting during throttling.

---

docs/source/api/api.rst
docs/source/conf.py
docs/source/mesh/painting.rst
docs/source/results/algorithms/projected-fftpower.rst
docs/source/results/algorithms/three-pt-cf.rst
nbodykit/__init__.py
nbodykit/algorithms/paircount_tpcf/estimators.py
nbodykit/base/catalog.py
nbodykit/base/mesh.py
nbodykit/cosmology/linearnbody.py
nbodykit/source/catalog/subvolumes.py

This PR fixes a few errors in the documentation, related to the compilers.
Also add some text about painting mesh object to a Field object, and applying transfer functions.

Documentation updates

---

nbodykit/algorithms/pair_counters/simbox.py
nbodykit/tests/test_transform.py
nbodykit/transform.py

the old map_blocks implementation was more of a hack. The apply_gufunc implementation reads more native and actually fixed problems by eliminated the explicit rechunking line when running simplehod on a large catalog.

Use da.apply_gufunc for Sky transforms

---

nbodykit/algorithms/pair_counters/domain.py
nbodykit/algorithms/pair_counters/simbox.py
nbodykit/algorithms/paircount_tpcf/tests/test_projected.py
nbodykit/algorithms/paircount_tpcf/tpcf.py
nbodykit/algorithms/threeptcf.py

This PR allows setting the position column to SimulationBox2PCF and pair counter.

Allow setting position column to 2PCF algorithms.

---

nbodykit/algorithms/tests/test_conv_power.py
nbodykit/algorithms/zhist.py

Because if there is no data the number density is zero.

zhist shall extrapolate to zero.

---

nbodykit/io/hdf.py
nbodykit/io/tests/test_hdf.py

This PR eases support on reading cosmohdf5 files.

Allow reading header attrs from a HDF file.

---

nbodykit/base/catalog.py
nbodykit/base/tests/test_catalog.py

- Fixes a bug sorting by Float32.
- Add a persist method that persists some columns into memory to form a new catalog.

Sorting of Float32 columns and Persist method

---

nbodykit/algorithms/convpower/fkp.py

Stumbled across this typo today 😊

Fix a typo in FKP

---

CHANGES.rst
nbodykit/source/mesh/catalog.py

Fix bug from issue https://github.com/bccp/nbodykit/issues/575

Fix painting bug in CatalogMesh

---

docs/source/catalogs/reading.ipynb
nbodykit/source/catalog/array.py

Update CSV example and add array catalog example.
CSV example now includes how to stack columns into position.

Update CSV example and add array catalog example

---

nbodykit/base/catalog.py
nbodykit/io/base.py
nbodykit/io/tests/test_stack.py

This PR is supposed to fix incompatibility with recent dask versions as seen in 
https://travis-ci.org/MP-Gadget/MP-Gadget/builds/551092287

Dask update ndim

---

nbodykit/extern/docrep.py

This avoids a warning about dedents.

update version of docrep.py.

---

nbodykit/io/base.py
nbodykit/io/bigfile.py
nbodykit/io/binary.py
nbodykit/io/csv.py
nbodykit/io/fits.py
nbodykit/io/gadget.py
nbodykit/io/hdf.py
nbodykit/io/stack.py
nbodykit/io/tests/test_binary.py
nbodykit/source/catalog/file.py
nbodykit/source/catalog/tests/test_file.py

This PR adds an example using a customized FileType in test_file.py.
Some clean up to make it slightly easier to use FileType.
Adding a FileCatalog class.

FileType + FileCatalog cleanup

---

nbodykit/io/csv.py

The behavior of read_csv has changed in pandas 1.1.

Check all columns are defined in names.

---

docs/source/catalogs/common-operations.ipynb
docs/source/catalogs/mock-data.ipynb
nbodykit/source/catalog/tests/test_hod.py
nbodykit/tests/test_lab.py
nbodykit/tests/test_transform.py
nbodykit/transform.py
nersc/example.py

Fix the way RSD is added to positions

---

nbodykit/cosmology/power/__init__.py
nbodykit/transform.py

Fix the build
