- contrib/MBIIDMO.py
Preliminary support for RSD and position. The position factor
0.001 converts from kpc/h to Mpc/h (conventional in nbodykit),
the vel factor depends on the redshift, and we are still looking for
a formula; when it is available we will add the formula to the documentation.
The files on Edison are at:
/global/u2/v/vat/mb2dmo/datato_nickhand/
Format described as
1) Files in MBII Hydro :-
mb2_pos : Subhalo position - (float32,3)
mb2_mass : Subhalo mass - float64
mb2_vel : Subhalo velocity - (float32,3)
2) Files in MBII Dark matter-only :-
dmo_pos : Subhalo position - (float32,3)
dmo_mass : Subhalo mass - float64
dmo_vel : Subhalo velocity - (float32,3)
> Add a reader for MBII and DMO matched catalog from Ananth.

- nbodykit/files.py
- nbodykit/plugins/HaloFilePainter.py
- nbodykit/plugins/TPMSnapshotPainter.py
- nbodykit/plugins/__init__.py
* added a function to files.py to read the 2D power plain text file
* reverting back to '-' rather than '&' for optional arguments since the later doesn't work in bash
> power 2D plain text reader; changing & to - for optional args

- nbodykit/measurepower.py
- nbodykit/plugins/Power1DStorage.py
- nbodykit/plugins/Power2DStorage.py
- nbodykit/plugins/__init__.py
- power.py
* los option specifies which direction mu is defined wrt
* only commented out old measurepower function now -- Yu,
feel free to delete once you've made edits
> combining measurepower for 1d and 2d cases; `los` option for power.py

- bin/power.py
- nbodykit/datasource/Pandas.py
- nbodykit/measurestats.py
* new behavior won't change any existing code
* use case is using different painters / transfer chains for 1st or 2nd field in cross-correlations (which I need for the density-velocity correlators)
> vectorizing ``transfer`` and ``painter`` keywords to compute_3d_power

- nbodykit/files.py
- nbodykit/plugins/Measurement1DStorage.py
- nbodykit/plugins/Measurement2DStorage.py
the current logic for output: 
* output complex power as successive columns
* update column names in header by appending "_real" and "_imag"
* the 2D reader looks for "_real"/"_imag" pairs in column names and reconstructs
the complex output, which it returns
* the 1D reader just does a numpy.loadtxt, so it returns an array with real/imag as successive columns
> fixes output bug for P(k,mu) + improvements

- nbodykit/extensionpoints.py
* Ntot was set to the number of columns, not number of rows
> fixes Ntot bug in default DataSource.read

- .travis.yml
- bin/power.py
- contrib/BlueTides.py
- examples/power/run.sh
- examples/power/test_cross_power.params
- examples/power/test_fofgroups.param
- examples/power/test_mwhite_halo.params
- examples/power/test_pandas_hdf.params
- examples/power/test_pandas_text.params
- examples/power/test_plaintext.params
- examples/power/test_tpmsnapshot_1d.params
- examples/power/test_tpmsnapshot_1d_corr.params
- examples/power/test_tpmsnapshot_2d.params
- nbodykit/__init__.py
- nbodykit/extensionpoints.py
- nbodykit/measurestats.py
- nbodykit/plugins/transfer/TransferFunction.py
- nbodykit/utils/taskmanager.py
* power examples have been updated to use YAML syntax -- CI won't succeed until latest pmesh change updated but works on laptop 
* I've implemented a basic first pass at doing "help", "defaults", "choices" in the YAML parser in power.py -- maybe @rainwoodman can take a look and spice it up a bit
A few things to note: 
* in the ``construct_fields`` function which makes the tuples of (DataSource, Painter, Transfer), I also had to pass in any `X` options and load them, so that the X options can be specified in the config file (in addition to the command line)
* Maybe we want to make the default Transfer chain [NormalizeDC, RemoveDC, AnisotropicCIC]. It seems to be the the desired chain in nearly all of the cases...
> introduces TransferFunction plugins, YAML file parsing in power.py

- bin/nbkit.py
- bin/power.py
- examples/power/run.sh
- nbodykit/extensionpoints.py
- nbodykit/plugins.py
- nbodykit/plugins/algorithms/PeriodicBox.py
new API for handling config for algorithm
-- `config` now an option of the plugin ArgumentParser, which is designed to be
only run by nbkit.py
-- `config` parsing explicitly handled by a function of Algorithm
--  better definitions of an Action and Type for Fields in FFTPower
-- renames PeriodicPower to FFTPower
this closes #130
> config yaml reading done explicitly by Algorithm function

- nbodykit/fof.py
- nbodykit/plugins/algorithms/FOF.py
- nbodykit/plugins/datasource/FOFGroups.py
- nbodykit/plugins/datasource/FastPM.py
- nbodykit/plugins/datasource/HaloLabel.py
- nbodykit/plugins/datasource/TPMLabel.py
- nbodykit/plugins/datasource/TPMSnapshot.py
This PR removes the relative linking length requirement in nbodykit.fof.fof, and adds absolute linking length support.
nbodykit.fof has been refactored to eliminate some hackiness. The peak memory usage may have increased, hopefully it won't be a big issue.
if a relative linking length is provided, the datasource must provide a TotalLength attribute. Currently the code will fail. But we can play the datasource and measure the length.
> FOF absolute linking length

- contrib/BOSSChallengeMock.py
- nbodykit/extensionpoints.py
- nbodykit/measurestats.py
- nbodykit/plugins/datasource/TracerCatalog.py
- nbodykit/utils/config.py
adds a few things:
* db59c5b adds a decorator in extensionpts.py and a `cache_data` function to DataSource that can turn on/off cacheing of the return values of the `read()` function
* idea is that you could use decorator in DataSource Plugins if you always want to cache or use the `cache_data` function to turn it on/off 
*  cleaning up TracerCatalog to use randoms to define box and nbar -- more clean up needed
> DataSource cache function; TracerCatalog clean up

- bin/nbkit.py
- nbodykit/plugins/algorithms/PeriodicBox.py
changes:
* if `output` key is left blank in config file (which sets it to None), algorithms can interpret this as stdout
* only valid for Describe algorithm right now
* fixes an output bug in PeriodicBox multipoles
> fixes `output` handling in nbkit.py -- set `output=None` for stdout 

- bin/nbkit.py
- nbodykit/fkp.py
- nbodykit/measurestats.py
- nbodykit/utils/config.py
* a few tests about FKP recentering  --> should be to [-L/2, L/2] for correctness
* previous test of this issue was wrong, which I discovered when adding the test that all particles are within the box
> only root logs warning about ignored config parameters; FKP should recenter to [-L/2, L/2]

- .gitignore
- nersc/activate.sh
- nersc/build.sh
- nersc/deploy.sh
- nersc/nightly-build.cron
- nersc/nightly-build.sh
* the setup right now builds a `stable` source tar which tracks the `master` HEAD and a `latest` tarball which tracks the `develop` branch
* in `/usr/common/contrib/bccp/nbodykit`, there is a `nbodykit-latest.tar.gz` and `nbodykit-stable.tar.gz`, as well as `activate.sh`
* the intended usage is then `source /usr/common/contrib/bccp/nbodykit/activate.sh`. If no arguments are provided, the `stable` tar ball is loaded and `latest` and `stable` can be passed to the script too. 
* the script `nightly-build.sh` installs the head of develop and master from github and installs the dependencies as well -- the dependencies take ~10-20 minutes to install because of `pfft-python` so eventually it would be good to implement some sort of version checking
* `bash nightly-build.cron` will add a cron job …
> potential build framework with nightly cron jobs

- nbodykit/measurestats.py
- nbodykit/plugins/algorithms/BianchiFFTPower.py
- nbodykit/plugins/algorithms/PeriodicBox.py
- nbodykit/utils/meshtools.py
* this introduces a mesh iterator that can apply a function slab-by-slab, which should help the readability of the code
> cleaning up measurestats with mesh iterator

- examples/fiber_collisions/test_fc.params
- examples/subsample/test_tpmsnapshot_mwhite.params
- nbodykit/plugins/algorithms/FiberCollisions.py
- nbodykit/plugins/algorithms/Subsample.py
- nbodykit/plugins/datasource/UniformBox.py
* use the new function `local_random_state` from `utils` module
* uses a global seed to generate new random seeds (any 32 bit integer) for all ranks
* hopefully this is good enough to reduce any possible correlations between random numbers on different ranks
* also fixes a bug in Subsample where the random seed wasn't being used
> Cleans up the parallel random seeds in several places

- bin/nbkit.py
- nbodykit/__init__.py
- nbodykit/core/algorithms/FiberCollisions.py
- nbodykit/plugins/__init__.py
- nbodykit/plugins/manager.py
I don't think the registry attribute is necessary
handling everything through plugin_manager simplifies a lot of the code
> remove `registry` from plugins; handle everything through plugin_manager

- nbodykit/core/algorithms/FOF6D.py
- nbodykit/core/algorithms/FiberCollisions.py
- nbodykit/core/algorithms/TraceHalo.py
- nbodykit/core/datasource/FOFGroups.py
- nbodykit/core/datasource/Pandas.py
- nbodykit/core/datasource/RaDecRedshift.py
- nbodykit/core/datasource/Subsample.py
- nbodykit/dataset.py
- nbodykit/distributedarray.py
- nbodykit/fof.py
follows up on #259 -- hopefully I didn't miss any
maybe this solves #260
> adding explicit numpy.dtype calls to avoid numpy bug

- nbodykit/meshtools.py
- nbodykit/mockmaker.py
addresses #288, although not completely. SlabIterator in its current form should only be used in 3D (hence, the "slab").  I think it mostly works in any dimension at the moment, but need to think about the non-singular plane and Hermitian weights. 
What did you have in mind for this, @rainwoodman ? Did you want to be able to do 1D and 2D Zel'dovich particles? Also, see rainwoodman/pmesh#17 for the case of 1D particle mesh
> addresses Poisson sampling in N-dimensions 

- .travis.yml
- nersc/activate.sh
- nersc/build_requirements.txt
- nersc/nightly-build.sh
- requirements.txt
This is in preparation for handling different versions on nersc:
* nightly build script activates conda environments for python 2.7, 3.5 stored in  `/usr/common/contrib/bccp/nbodykit/build-envs/2.7-nbodykit-base`. These were created from the new `build_requirements.txt` file. This avoids a bunch of potential conflicts with the base anaconda distributions when installing dependencies
* the `activate.sh` script now recognizes `v2.0` as an option (`stable` and `latest` stay the same for now)
* cleaned up the Travis dependencies, let's see if I broke anything
> cleaning up nightly build scripts

- CHANGES.rst
- nbodykit/base/catalog.py
- nbodykit/cosmology/core.py
- nbodykit/cosmology/ehpower.py
- nbodykit/io/bigfile.py
- nbodykit/source/catalog/hod.py
- nbodykit/source/catalog/tests/test_catalog.py
- nbodykit/source/catalog/tests/test_hod.py
I think this is the most straightforward short-term solution to #328. Use `nbodykit.utils.JSONEncoder` to simply write out the JSON string in the BigFile
> save source attrs as JSON string representation (#328)

- nbodykit/io/base.py
may be the reason of an OOM error reading runpb snapshots.
> list(self) was fishy.

- nbodykit/transform.py
halotools 0.5 removed a few classes that were deprecated since 0.4. (https://github.com/astropy/halotools/pull/709)
This commit updates the references to the newer ones.
It appears that after the commit the code works with both halotools 0.4.0 and 0.5.0
> Stop using obsolete names since halotools-0.4 and removed in 0.5

- nbodykit/cosmology/__init__.py
- nbodykit/cosmology/background.py
- nbodykit/cosmology/core.py
- nbodykit/cosmology/ehpower.py
- nbodykit/cosmology/tests/test_cosmology.py
> WIP: use the ode solver for growth factor and growth rate.

- .travis.yml
- docs/Makefile
- docs/apidoc.sh
- docs/conf.py
- docs/dataset.rst
- docs/environment.yml
- docs/extending.rst
- docs/generate_plugins_list.py
- docs/overview.rst
- docs/running.rst
- nbodykit/core/datasource/FastPM.py
- nbodykit/test/test_paint.py
- readthedocs.yml
This does a couple of things:
* clean up broken links, etc in the legacy docs
* fixes the legacy tests -- 0.1.10 was never tagged as a release due to failed travis tests
> clean up legacy docs and tests

- .travis.yml
- CHANGES.rst
- nbodykit/io/__init__.py
- nbodykit/io/fits.py
- nbodykit/io/tests/test_fits.py
- nbodykit/source/catalog/__init__.py
- nbodykit/source/catalog/file.py
- requirements-extras.txt
Very basic functionality for now, but should be a good start.
As expected, fitsio does seem to outperform astropy's fits reader,
so we'll use fitsio for now
> adding a basic FITS reader using fitsio

- nbodykit/algorithms/__init__.py
- nbodykit/algorithms/fof.py
- nbodykit/algorithms/kdtree.py
- nbodykit/algorithms/tests/test_fof.py
- nbodykit/algorithms/tests/test_kddensity.py
- nbodykit/source/catalog/array.py
- nbodykit/source/catalog/tests/test_hod.py
This PR adds PeakPosition and PeakVelocity to FOF.
The column to define the peak is passed in as peakcolumn.
I added an algorithm KDDensity for a coarse estimation of density. This can be combined with FOF to find peak positions and velocities in the catalogue. The example is in test_fof.py
> WIP: Finding peak properties with FOF

- nbodykit/tests/test_transform.py
- nbodykit/transform.py
This can be triggered when we generate an empty FOF catalog, and saving it to disk. The Selection column is a ConstantArray of size 1. But the squeeze method makes it a scalar -- which has no well defined __len__ in dask. This PR removes the squeeze
> Fix len() error on dask array with ConstantArray of size 1.

- docs/source/install.rst
> Add some notes about login nodes.

- nbodykit/algorithms/fof.py
- nbodykit/algorithms/tests/test_fof.py
FOF used to give unstable results when the boxsize is close to the size of domain and there are particles outside of the box.
I do not have an isolated test case but this seems to be related to the failure of a test case in fastpm-python.
The labels of a halo found from 4 ranks is broken into several when running with 1 rank.
However,  run with 1 rank without periodic boundary these particles become 1 halo. 
After adding the wrapping into the boundary these particles become 1 halo on a single rank as well.
> FOF gives unstable results at lower number of ranks

- nbodykit/algorithms/fof.py
- nbodykit/algorithms/tests/test_fof.py
This addresses #417, where a boxsize is absurdly required for a non-periodic dataset. I guess in other places of the code we still mostly assume periodic boundary. I wonder if this simplifies the FiberAssignment algorithm?
> Adding Non-periodic support to FOF.

- nbodykit/style/notebook.mplstyle
It is not always properly installed on the target system. For example jupyter-dev.nersc.gov has a crippled latex and causes the notebook to fail to run. Does the font look very bad without using Tex?
> I suggest not using latex

- nbodykit/base/catalogmesh.py
- nbodykit/source/catalogmesh/tests/test_species.py
See the last cells of the pdf file:
[mozilla.pdf](https://github.com/bccp/nbodykit/files/1408694/mozilla.pdf)
The mean is not properly normalized when interlacing is enabled. Looks like some of the buffer reuse is incorrect.
> Interlaced species

- nbodykit/algorithms/fof.py
Workaround of https://github.com/numpy/numpy/issues/9137.
It only becomes issue in recent versions of numpy where casting
rules are stricter.
> Fix crash with numpy 1.13.3

- nbodykit/io/bigfile.py
- nbodykit/io/tests/test_bigfile.py
This improves the usability of reading a saved catalog.
A saved catalog saves the attrs in Header column, but when we
read it in from BigFileCatalog the default was not to use
that column, creating confusions.
Original email report of the issue:
```
I’m having some difficulty saving and reading files using CatalogSource. I have a simple script like below to save the ArrayCatalog data:
particle_data = {}
particle_data['Position'] = pos
particle_data['Velocity'] = vel
particle_data['ID'] = Id
cat = NBlab.ArrayCatalog(particle_data, BoxSize=header['boxsize'])
cat.save(dir+’/Matter', ["Position", "Velocity"])
This saves everything nicely into the Matter directory. But Later when I try to read in this data using something like
cat = BigFileCatalog(‘Matter’)
I get the following: “Error: Dataset …
```
> Allow automatic discovery of header from a BigFile.

- nbodykit/base/catalog.py
- nbodykit/base/tests/test_catalog.py
Do not copy attributes when view is used.
> Copy Attributes when copy is used.

- nbodykit/base/catalog.py
- nbodykit/base/tests/test_catalog.py
- nbodykit/io/base.py
- nbodykit/source/catalog/hod.py
This fixes #431.
* introduces "default" columns --> these are columns that are defined via class member functions
* add a metaclass to CatalogSource that picks up default columns and hard coded columns that are part of the class
* add ``is_default`` attribute to ColumnAccessor, letting users test if a column is default; I thought this was better than a ``defaults`` list, which would change as columns are overriden 
* filter out and do not save defaults in CatalogSource.save()
> Add default columns and do not save them to disk

- nbodykit/__init__.py
- nbodykit/base/catalogmesh.py
- nbodykit/base/tests/test_catalogmesh.py
- nbodykit/tests/test_options.py
reported by @zdplayground
See
https://github.com/bccp/nbodykit/commit/4e41aab09c4c7caa702fe7b9a31f1b54c5923f07#commitcomment-25540401
> Fix Memory Error when data is larger than chunk size in paint().

- nbodykit/base/catalogmesh.py
This requires version 0.1.37 of pmesh.
> Add support to PCS resampling windows.

- nbodykit/algorithms/convpower.py
- nbodykit/meshtools.py
See [#458](https://github.com/bccp/nbodykit/pull/458).
> Fix docstrings

- nbodykit/algorithms/pair_counters/domain.py
- nbodykit/algorithms/pair_counters/tests/test_1d.py
- nbodykit/algorithms/paircount_tpcf/tests/test_angular.py
Survey data does not start from [0, 0, 0]. Thus we need to set
the left edge and right edge properly.
This is one of the cause of a crash in @martinjameswhite's script.
> Decompose to the correct boxsize for surveydata

- nbodykit/io/bigfile.py
A typo causes ./ used and a File object is returned instead of
a BigBlock object.
```
~/anaconda3/install/lib/python3.6/site-packages/nbodykit/source/catalog/file.py in __init__(self, filetype, args, kwargs, comm)
43         # bcast the FileStack
44         if self.comm.rank == 0:
---> 45             self._source = FileStack(filetype, *args, **kwargs)
46         else:
47             self._source = None
~/anaconda3/install/lib/python3.6/site-packages/nbodykit/io/stack.py in __init__(self, filetype, path, *args, **kwargs)
50         else:
51             raise ValueError("'path' should be a string or a list of strings")
---> 52         self.files = [filetype(fn, *args, **kwargs) for fn in filenames]
53         self.sizes = numpy.array([len(f) for f in self.files], dtype='i8')
54 …
```
> fix bigfile attrs when there is no header block.

- nbodykit/io/bigfile.py
As specified in the documentation. The rational is that
this way one can always easily specify a special header block in not
in the dataset. If it were relative to the dataset then there is
no way to load the header if it is outside.
This fix solves a few occasions where scripts mysteriously stopped
working when loading catalog.
> bigfile shall look for header starting from root.

- docs/source/results/algorithms/index.rst
- docs/source/results/algorithms/paircount.rst
- docs/source/results/algorithms/projected-fftpower.rst
- docs/source/results/algorithms/three-pt-cf.rst
- docs/source/results/algorithms/two-pt-cf.rst
- nbodykit/algorithms/pair_counters/corrfunc/mocks.py
- nbodykit/algorithms/pair_counters/corrfunc/theory.py
- nbodykit/algorithms/pair_counters/domain.py
- nbodykit/algorithms/pair_counters/tests/test_1d.py
- nbodykit/source/catalog/uniform.py
This PR fixes the crash if data and random are of different dtypes in SurveyDataPairCount and SimulationBoxPairCount. Both use corrfunc which doesn't handle this case. 
Therefore we cast the input to the type of pos2 instead of throwing a mysterious CorrFunc error.
> FIX: PairCount crashes if two data sets are of different dtypes.

- nbodykit/cosmology/linearnbody.py
- nbodykit/cosmology/tests/test_linearnbody.py
This PR adds the linear theory correspondant of a nbody simulation.
The initial condition can be set from CLASS transfer function.
The equations are symplectic. It can also be used to construct back-scaled initial conditions, when ran in inverse with high precision.
> Linear theory correspondant of a nbody simulation.

- nbodykit/mockmaker.py
We shall tag a release after this, such that we can tag an incompatible release of pmesh; which the faster lognormal branch will eventually depend on.
> Avoid using pm.x; it will be removed in pmesh 0.1.43.

- nbodykit/binned_statistic.py
- nbodykit/tests/test_binned_stat.py
The take method behaves more or less like the traditional numpy indexing.
Either a boolean mask of the same shape of data, or boolean masks along
each axis is accept. It is more powerful and sometimes allows more
intuitive code segments than the current sel method; see the example in
docstring.
The full boolean mask is projected along each axis then 'and'ed to the
given mask along the axis.
If a list of indices is given along any axis, it is first converted to
a mask.
In the end the booleans are converted to lists because the finalize method
takes only indices.
> Add a take method to BinnedStatistic.

- nbodykit/algorithms/pair_counters/tests/test_1d.py
- nbodykit/algorithms/pair_counters/tests/test_2d.py
- nbodykit/algorithms/pair_counters/tests/test_angular.py
- nbodykit/algorithms/pair_counters/tests/test_projected.py
- nbodykit/algorithms/tests/test_cgm.py
- nbodykit/algorithms/tests/test_conv_power.py
- nbodykit/algorithms/tests/test_fftrecon.py
- nbodykit/algorithms/tests/test_zhist.py
- nbodykit/base/mesh.py
- nbodykit/base/tests/test_catalog.py
- nbodykit/base/tests/test_catalogmesh.py
- nbodykit/mockmaker.py
- nbodykit/mpirng.py
- nbodykit/source/catalog/lognormal.py
- nbodykit/source/catalog/tests/test_lognormal.py
- nbodykit/source/catalog/tests/test_uniform.py
- nbodykit/source/catalog/uniform.py
- nbodykit/tests/test_mpirng.py
- nbodykit/tests/test_transform.py
- nbodykit/tests/test_utils.py
- nbodykit/utils.py
This PR replaces #492 . The reason is this one relies on a different (cleaner) API in pmesh.
This API of pmesh exposes transposed / untransposed Fields as different subclasses of BaseComplexField, rather than requiring different pm objects.
> Improving scaling of LogNormalCatalog (v2)

- nbodykit/algorithms/convpower.py
- nbodykit/algorithms/fftpower.py
- nbodykit/algorithms/fftrecon.py
- nbodykit/base/catalogmesh.py
- nbodykit/base/mesh.py
- nbodykit/base/tests/test_catalog.py
- nbodykit/base/tests/test_catalogmesh.py
- nbodykit/base/tests/test_mesh.py
- nbodykit/source/catalog/tests/test_lognormal.py
- nbodykit/source/catalogmesh/fkp.py
- nbodykit/source/catalogmesh/species.py
- nbodykit/source/catalogmesh/tests/test_fkp.py
- nbodykit/source/catalogmesh/tests/test_species.py
- nbodykit/source/mesh/tests/test_bigfile.py
- nbodykit/tests/test_lab.py
This is required to add a compute method to MeshSource. Because
if CatalogMesh is a CatalogSource then CatalogSource.compute comes
into the way.
I think this PR also sheds some light on how to deal with the temporary
variables created during FKP/convpower. They probably shall be saved
as attributes of the CatalogMesh objects directly, rather than stored
as columns of the underlying sources.
> Add compute method and remove Catalog interface from CatalogMesh.

- nbodykit/algorithms/fftcorr.py
- nbodykit/algorithms/fftpower.py
- nbodykit/algorithms/tests/test_fftcorr.py
- nbodykit/algorithms/tests/test_fftpower.py
- nbodykit/base/tests/test_catalog.py
- nbodykit/binned_statistic.py
This PR also changes the file format of FFTPower.save and FFTCorr.save,
as they now also need to save the centers, which are no longer strictly
derived from the edges.
BinnedStatistic is extended to accept bin label coordinates as an external
argument. Of course rebinning would totally mess up the centers.
ProjectedFFTPower is left unchanged because it may eventually be rewritten with
the new 'transpose interface' of pmesh and improved support on 2d / 1d.
The edge property on FFTPower and FFTCorr, attached by the run method are now
removed. Use the edge property of the power object and corr object instead.
The 'run' function of FFTPower and FFTCorr are changed to be more 'function' like.
> FFTPower and FFTCorr supports Unique |k| or |r| bins. 

- nbodykit/base/catalog.py
- nbodykit/base/decomposed.py
- nbodykit/base/tests/test_decomposed.py
- nbodykit/source/catalog/lognormal.py
This PR adds a decompose method that allows decomposing a catalog to a given domain decompostion policy. The current API focuses on the spatial decomposition.
> Domain Decompose of a catalog

- nbodykit/__init__.py
- nbodykit/algorithms/pair_counters/domain.py
Due to https://github.com/dask/dask/issues/3674 tests in Corrfunc based pair counters are failing due to the assignment operator upon the return value of dask.
> WIP: Workaround dask 0.18.1 stopped returning views in compute()

- nbodykit/algorithms/fftpower.py
- nbodykit/meshtools.py
- nbodykit/mockmaker.py
In numpy 1.15 divide by zero is separate from invalid errors. This PR silences them so we don't get too many warning messages.
> Ignore divide errors.

- nbodykit/base/catalog.py
Since dask 0.19.0 we start to get OOM errors, because
dask stopped applying culling to the default compute method when
optimize_graph is False.
We still do not want optimize_graph because it permutes the order
ing of column and row access in a unfavorable way; but we do
want the culling. So implement the culling in the new
graph protocal and see if it helps.
> Apply the culling optimization to ColumnAccessor.

- nbodykit/__init__.py
We really shall look into rewriting the paint algorithm with dask,
off loading the memory usage bound to dask.
> Reduce the paint size for systems with lower mem per core

- nbodykit/io/bigfile.py
- nbodykit/io/tests/test_bigfile.py
This is needed to support the new fastpm lightcone format
where the lightcone aemit index is saved only for
particle type 1.
> Aggregate attrs of header and the main datasets.

- nbodykit/algorithms/fof.py
- nbodykit/base/catalog.py
- nbodykit/io/csv.py
- nbodykit/source/mesh/bigfile.py
- nbodykit/transform.py
On some occasions when code is ran in e.g. a notebook,
numpy.sum is imported to replace sum, and the behaviro of
numpy.sum([]) is to 0.0 rather than builtin.sum([]) which returns 0.
numpy.sum([]) returning 0.0 causes downstream code expecting integers to fail,
thus copying the code out of nbodykit won't work.
We shall not serve as an poor example in this context.
> when summing integers, use numpy.sum.

- nbodykit/__init__.py
- nbodykit/base/catalog.py
- nbodykit/base/mesh.py
- nbodykit/base/tests/test_catalog.py
- nbodykit/io/base.py
- nbodykit/io/bigfile.py
- nbodykit/io/binary.py
- nbodykit/io/csv.py
- nbodykit/io/fits.py
- nbodykit/io/gadget.py
- nbodykit/io/hdf.py
- nbodykit/io/stack.py
- nbodykit/io/tests/test_bigfile.py
- nbodykit/mockmaker.py
- nbodykit/source/catalog/file.py
- nbodykit/source/mesh/bigfile.py
- nbodykit/source/mesh/catalog.py
- nbodykit/tests/test_cache.py
- nbodykit/tests/test_options.py
Combined with several threading fixes in bigfile, this PR improves the support with dask clusters.
Two new functions are added: nbodykit.use_distributed and nbodykit.use_mpi. For dask clusters, initialize using use_distributed. for MPI clustrers, initialize using use_mpi. The MPI cluster mode is the default.
The global cache context manager is removed. The opportunistic caching it is now always enabled in MPI mode (when dask's synchronous scheduler is used); and always disabled in distributed mode, when the distributed scheduler is used.
The pickling trick was from mpi4py's bitbucket issue : https://bitbucket.org/mpi4py/mpi4py/issues/104/#comment-47225639
The singleton initialization needs to be revisited after the distributed PR https://github.com/dask/distributed/pull/2391 is merged.
> Improve usage under pure dask cluster mode.

- nbodykit/io/base.py
- nbodykit/io/tests/test_bigfile.py
If the column is sliced with stepping, then toret is no longer C contiguous and the view fails. This was triggered when using dask.array.store on the column of a catalog.
> IO reshape of sliced array.

- nbodykit/base/catalog.py
- nbodykit/transform.py
1. Fixed a bug regarding calculation of total sliced size.
2. Give ConstantArray a dask name, such that dask does not hang trying to tokenize huge ConstantArray objects.
3. Use numpy.copy to decouple sliced columns from original data. This improves the memory footprint substantially when slicing is subsampling; previously the new computed array will have references to chunks of the full original data.
> A few improvements to slicing of a catalog.

- nbodykit/base/catalog.py
- nbodykit/source/mesh/catalog.py
- nbodykit/source/mesh/tests/test_catalogmesh.py
Before this PR we used a simple formula 1 / nbar, which is incorrect if the data is weighted.
@martinjameswhite suggested an alternative formula:
``` V / (sum w**2 / (sum w)**2) ```
It reverts to ```V/N``` when w is unweighted. This expression is also consistent with the shotnoise combination equation in MultipleSpeciesCatalog.
I strongly suspect this was a regression. But anyhow here is the fix.
A test case is added to make sure it does not break again.
> Fix shotnoise estimation of weighted to_mesh() calls.

- nbodykit/extern/docrep.py
This fixes a warning that contaminates the output of tests.
> Update docrep to 0.2.5

- nbodykit/base/catalog.py
- nbodykit/tests/test_distributed.py
- nbodykit/tests/test_options.py
For the current data chunking there is no need to lock,
locking also breaks distributed scheduler.
see:
dask/dask#4349
> Fix unable to pickle _thread.lock object error during store.

- nbodykit/base/catalog.py
- nbodykit/base/tests/test_catalog.py
Catalog.save may return futures when compute=False
The use case is if we know some columns can be computed more efficiently if they are computed together, then we can do the store operation together.
> Catalog.save may return futures.

- nbodykit/transform.py
Shall not change this because internally we use the function to feed halotools which expects proper Mpc/h. But it did break simplehod.
> Note about unit of HaloRadius.

- nbodykit/source/catalog/file.py
- nbodykit/source/catalog/tests/test_file.py
This PR only includes a query interface that supports querying on a range in the file.
It returns a new FileCatalog of the same time, but with references to a new range in the file.
I do not like the current implementation, as it feels like I haven't plumbed through the details of catalog object creation, which seems to be rather convoluted due to hacks like this -- expanding the class for specialized cases ..
> Add initial query interface to FileCatalog.

- nbodykit/io/gadget.py
This PR adds support reading the Gadget1 variant binary format, where each block is prefixed by an additional 16 byte header.
> Add support to Gadget1 variant binary format.

- nbodykit/tests/test_utils.py
- nbodykit/utils.py
Previously we would have silently shifted the bins.
> fix DistributedArray.bincount when input has gaps.

- nbodykit/algorithms/threeptcf.py
The replace method in Sympy no longer recognize string exprs.
Must explicitly call sympify on the expr.
This may be a regression bug on Sympy side, but we do not care too
much about this.
> Compatibility with sympy 1.4.

- docs/environment.yml
Removing conda-forge from the enviroment may have significantly speeded up the build process.
The test build took less than 500 seconds.
> Remove conda-forge from rtfd environment

- nbodykit/algorithms/fibercollisions.py
This should address #584. The previous algorithm wraps particles
with periodic boundary and may have connected points near the edges
incorrectly.
> Center the particles in fiber collision.

- nbodykit/algorithms/fof.py
- nbodykit/algorithms/tests/test_fiber_colls.py
- nbodykit/algorithms/tests/test_fof.py
This is the reason #584 mis-behaves. 
(https://github.com/bccp/nbodykit/issues/584#issuecomment-494019300)
> Reserve label == 0 for FOF unconnected, even if fully connected

- nbodykit/io/stack.py
Since we claim a glob is supported, we should not only support
'*'.
> Allow any glob pattern in file names.

- nbodykit/filters.py
Fixed the return statement in line 58.  Now the Gaussian filter is applied properly to the mesh `v`.
> Fixed bug in Gaussian filter in nbodykit/filters.py

- nbodykit/algorithms/convpower/catalog.py
- nbodykit/algorithms/convpower/fkp.py
- nbodykit/algorithms/fftpower.py
Fixed a bug in the nbodykit odd multipoles:
--correct the definition of  "hermitian_symmetric" to use the "compressed" attribute of the mesh
--ensure that coordinates are real even when mesh is complex
--changed default mesh type to 'c16.' added explanation for the user that dtype='f8' is faster for even multipoles but yields incorrect odd multipoles in the presence of the wide-angle effect.
> Correct odd multipoles in presence of wide-angle effect

- nbodykit/algorithms/zhist.py
zhist.py fails when bins is a scalar. I think this is because "comm" in lines 63 and 64 should be "self.comm."
> Fixed bug in zhist.py

- nbodykit/meshtools.py
At kx=ky=kz=0, in slab.mu(los), the norm2 is 0 and thus mu is nan.  This leads to a nan in legpoly which propagates into nans for all multipoles in the bin containing k=0 for multipoles other than the monopole.  following suggestion of @michaelJwilson, modify SlabIterator.mu in meshtools to fix this issue.
> fix to meshtools to avoid nans in legpoly at k=0

- nbodykit/base/mesh.py
- nbodykit/base/tests/test_mesh.py
Also fix the test case which were not testing the complex case.
Reported by wuyiheng@shao.ac.cn:
from nbodykit.lab import ArrayMesh
import numpy
data = numpy.random.random(size=(128,128,128))
mesh = ArrayMesh(data, BoxSize=1.0)
mesh.save("mesh",dataset="LinearDensityK",mode="complex")
And next is the result in the attrs file
BoxSize <f8 3 000000000000F03F000000000000F03F000000000000F03F #HUMANE [ 1 1 1 ]
Nmesh <i8 3 800000000000000080000000000000008000000000000000 #HUMANE [ 128 128 128 ]
ndarray.shape <i8 9 800000000000000080000000000000008000000000000000800000000000000080000000000000008000000000000000410000000000000041000000000000004100000000000000 #HUMANE [ 128 128 128 128 128 128 65 65 65 ]
the shape should have been a 3 vector.
> Fix wrong shape of complex mesh save.

- docs/source/index.rst
Updating to what I am guessing was meant.
I can also add an `import numpy` to the import statement above for self-containedness.
> DOC fix random uniform call in 1 minute intro

- nbodykit/source/mesh/catalog.py
> Fix `toret.attrs["W2"]`
